//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Management.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Management.Messages.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain message type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotObtainMessageType {
            get {
                return ResourceManager.GetString("CannotObtainMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to copy all the messages from source queue &apos;{0}&apos; to destination queue &apos;{1}&apos;?.
        /// </summary>
        internal static string ConfirmCopyAll {
            get {
                return ResourceManager.GetString("ConfirmCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the selected message(s).  Continue?.
        /// </summary>
        internal static string ConfirmMessageDeletion {
            get {
                return ResourceManager.GetString("ConfirmMessageDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to move all the messages from source queue &apos;{0}&apos; to destination queue &apos;{1}&apos;?.
        /// </summary>
        internal static string ConfirmMoveAll {
            get {
                return ResourceManager.GetString("ConfirmMoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to return all the messages from source queue &apos;{0}&apos; to their respective recipient queue?.
        /// </summary>
        internal static string ConfirmReturnAllToSourceQueue {
            get {
                return ResourceManager.GetString("ConfirmReturnAllToSourceQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A total of {0} messages were copied from source queue &apos;{1}&apos; to destination queue &apos;{2}&apos;..
        /// </summary>
        internal static string CopyAllComplete {
            get {
                return ResourceManager.GetString("CopyAllComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove message with id &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotRemoveMessage {
            get {
                return ResourceManager.GetString("CouldNotRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with id &apos;{0}&apos; has been enqueued on queue &apos;{1}&apos;..
        /// </summary>
        internal static string EnqueuedMessage {
            get {
                return ResourceManager.GetString("EnqueuedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageArrowBack {
            get {
                object obj = ResourceManager.GetObject("ImageArrowBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMessage {
            get {
                object obj = ResourceManager.GetObject("ImageMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMessageCopy {
            get {
                object obj = ResourceManager.GetObject("ImageMessageCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMessageMove {
            get {
                object obj = ResourceManager.GetObject("ImageMessageMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMessageRelease {
            get {
                object obj = ResourceManager.GetObject("ImageMessageRelease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageStopIgnoring {
            get {
                object obj = ResourceManager.GetObject("ImageStopIgnoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display message with id &apos;{0}&apos; since it is compressed..
        /// </summary>
        internal static string MessageCompressed {
            get {
                return ResourceManager.GetString("MessageCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display message with id &apos;{0}&apos; since it is encrypted..
        /// </summary>
        internal static string MessageEncrypted {
            get {
                return ResourceManager.GetString("MessageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transport message assembly qualified type name &apos;{0}&apos; does not exactly match the type returned by the .NET runtime &apos;{1}&apos;..
        /// </summary>
        internal static string MessageTypeMismatch {
            get {
                return ResourceManager.GetString("MessageTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A total of {0} messages were moved from source queue &apos;{1}&apos; to destination queue &apos;{2}&apos;..
        /// </summary>
        internal static string MoveAllComplete {
            get {
                return ResourceManager.GetString("MoveAllComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message has not been checked..
        /// </summary>
        internal static string NoMessageChecked {
            get {
                return ResourceManager.GetString("NoMessageChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serializer type has been specified. The DefaultSerializer will be used..
        /// </summary>
        internal static string NoSerializerDefaultSerializer {
            get {
                return ResourceManager.GetString("NoSerializerDefaultSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged message with id &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string RemovedMessage {
            get {
                return ResourceManager.GetString("RemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A total of {0} messages were returned from source queue &apos;{1}&apos; to their respective recipient queue..
        /// </summary>
        internal static string ReturnAllToSourceQueueComplete {
            get {
                return ResourceManager.GetString("ReturnAllToSourceQueueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer type &apos;{0}&apos; could not be created. The DefaultSerializer will be used.  Exception reported: {1].
        /// </summary>
        internal static string SerializerTypeExceptionDefaultSerializer {
            get {
                return ResourceManager.GetString("SerializerTypeExceptionDefaultSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the IQueueReader for the queue represented by the source queue uri..
        /// </summary>
        internal static string SourceQueueUriReader {
            get {
                return ResourceManager.GetString("SourceQueueUriReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with id &apos;{0}&apos; is no longer being ignored..
        /// </summary>
        internal static string StoppedIgnoringMessage {
            get {
                return ResourceManager.GetString("StoppedIgnoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        internal static string TextAcknowledge {
            get {
                return ResourceManager.GetString("TextAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all.
        /// </summary>
        internal static string TextCopyAll {
            get {
                return ResourceManager.GetString("TextCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get message.
        /// </summary>
        internal static string TextGetMessage {
            get {
                return ResourceManager.GetString("TextGetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string TextMessages {
            get {
                return ResourceManager.GetString("TextMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string TextMove {
            get {
                return ResourceManager.GetString("TextMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all.
        /// </summary>
        internal static string TextMoveAll {
            get {
                return ResourceManager.GetString("TextMoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh queues.
        /// </summary>
        internal static string TextRefreshQueues {
            get {
                return ResourceManager.GetString("TextRefreshQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string TextRelease {
            get {
                return ResourceManager.GetString("TextRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return all to source queue.
        /// </summary>
        internal static string TextReturnAllToSourceQueue {
            get {
                return ResourceManager.GetString("TextReturnAllToSourceQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to source queue.
        /// </summary>
        internal static string TextReturnToSourceQueue {
            get {
                return ResourceManager.GetString("TextReturnToSourceQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop ignoring.
        /// </summary>
        internal static string TextStopIgnoring {
            get {
                return ResourceManager.GetString("TextStopIgnoring", resourceCulture);
            }
        }
    }
}
