CREATE TABLE [dbo].[DataStore](
	[Name] [varchar](64) NOT NULL,
	[ConnectionString] [varchar](1024) NOT NULL,
	[ProviderName] [varchar](512) NOT NULL,
 CONSTRAINT [PK_DataStore] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
